export function queryElements(document) {
  return {
    form: document.querySelector("#job-form"),
    prompt: document.querySelector("#prompt"),
    stylePreset: document.querySelector("#stylePreset"),
    topology: document.querySelector("#topology"),
    textureDetail: document.querySelector("#textureDetail"),
    feedback: document.querySelector("#form-feedback"),
    submit: document.querySelector("#submit-job"),
    clearHistory: document.querySelector("#clear-history"),
    clearPreview: document.querySelector("#clear-preview"),
    downloadModel: document.querySelector("#download-model"),
    jobList: document.querySelector("#job-list"),
    suggestions: document.querySelector("#suggestions"),
    emptyState: document.querySelector("#empty-state"),
    pipelinePanel: document.querySelector("#pipeline-panel"),
    activePrompt: document.querySelector("#active-prompt"),
    activeProgress: document.querySelector("#active-progress"),
    progressFill: document.querySelector("#progress-fill"),
    progressBar: document.querySelector('[role="progressbar"]'),
    pipelineStages: document.querySelector("#pipeline-stages"),
    activeJobBadge: document.querySelector("#active-job-badge"),
    previewScene: document.querySelector("#preview-scene"),
    previewMode: document.querySelector("#preview-mode"),
    previewSubject: document.querySelector("#preview-subject"),
    previewCopy: document.querySelector("#preview-copy"),
    previewShape: document.querySelector("#preview-shape"),
    previewMaterial: document.querySelector("#preview-material"),
    previewStyle: document.querySelector("#preview-style"),
    previewTopology: document.querySelector("#preview-topology"),
    previewStageLabel: document.querySelector("#preview-stage-label"),
    debugSubject: document.querySelector("#debug-subject"),
    debugModifiers: document.querySelector("#debug-modifiers"),
    debugJson: document.querySelector("#debug-json"),
    debugScript: document.querySelector("#debug-script"),
  };
}
